version: "3.1"

services:
  mysql-db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./init/01-createTables.sql:/docker-entrypoint-initdb.d/01-createTables.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3323:3306"

  mysql-seed:
    build: ./init/mysql-seed
    depends_on:
      - mysql-db
    env_file:
      - .env
    volumes:
      - ./init/mysql-seed:/mysql-seed
    working_dir: /mysql-seed
    command: sh seed.sh

  redis:
    image: redis:7.2.1
    restart: always
    env_file:
      - .env
    ports:
      - "8090:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

  # dependency-check:
  #   image: owasp/dependency-check
  #   volumes:
  #     - ./../../ict3x03-team7-backend:/usr/src/dependency-check/data
  #   command:
  #     [
  #       '--scan',
  #       '/usr/src/dependency-check/data',
  #       '-f',
  #       'HTML',
  #       '-o',
  #       '/usr/src/dependency-check/data',
  #     ]
  #   environment:
  #     - TZ=UTC

volumes:
  mysql-data:
  redis-data:
